<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            // Store Management
            [
                'name' => 'View Store',
                'slug' => 'store.view',
                'description' => 'Can view store details and information',
                'group' => 'Store Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manage Store',
                'slug' => 'store.manage',
                'description' => 'Can edit store settings, themes, and configurations',
                'group' => 'Store Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'View Users',
                'slug' => 'store.view_users',
                'description' => 'Can view store users',
                'group' => 'Store Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Create Users',
                'slug' => 'store.create_users',
                'description' => 'Can create new store users',
                'group' => 'Store Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edit Users',
                'slug' => 'store.edit_users',
                'description' => 'Can edit store users',
                'group' => 'Store Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delete Users',
                'slug' => 'store.delete_users',
                'description' => 'Can delete store users',
                'group' => 'Store Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manage Users',
                'slug' => 'store.manage_users',
                'description' => 'Can manage store users, roles, and permissions',
                'group' => 'Store Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Product Management
            [
                'name' => 'View Products',
                'slug' => 'products.view',
                'description' => 'Can view products and product details',
                'group' => 'Product Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Create Products',
                'slug' => 'products.create',
                'description' => 'Can create new products',
                'group' => 'Product Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edit Products',
                'slug' => 'products.edit',
                'description' => 'Can edit existing products',
                'group' => 'Product Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delete Products',
                'slug' => 'products.delete',
                'description' => 'Can delete products',
                'group' => 'Product Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manage Stock',
                'slug' => 'products.manage_stock',
                'description' => 'Can manage product inventory and stock levels',
                'group' => 'Product Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Category Management
            [
                'name' => 'View Categories',
                'slug' => 'categories.view',
                'description' => 'Can view product categories',
                'group' => 'Category Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Create Categories',
                'slug' => 'categories.create',
                'description' => 'Can create new categories',
                'group' => 'Category Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edit Categories',
                'slug' => 'categories.edit',
                'description' => 'Can edit existing categories',
                'group' => 'Category Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delete Categories',
                'slug' => 'categories.delete',
                'description' => 'Can delete categories',
                'group' => 'Category Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Order Management
            [
                'name' => 'View Orders',
                'slug' => 'orders.view',
                'description' => 'Can view orders and order details',
                'group' => 'Order Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Create Orders',
                'slug' => 'orders.create',
                'description' => 'Can create new orders',
                'group' => 'Order Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edit Orders',
                'slug' => 'orders.edit',
                'description' => 'Can edit existing orders',
                'group' => 'Order Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delete Orders',
                'slug' => 'orders.delete',
                'description' => 'Can delete orders',
                'group' => 'Order Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Refund Orders',
                'slug' => 'orders.refund',
                'description' => 'Can process order refunds',
                'group' => 'Order Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Financial Management
            [
                'name' => 'View Expenses',
                'slug' => 'expenses.view',
                'description' => 'Can view business expenses',
                'group' => 'Financial Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Create Expenses',
                'slug' => 'expenses.create',
                'description' => 'Can create new expense entries',
                'group' => 'Financial Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edit Expenses',
                'slug' => 'expenses.edit',
                'description' => 'Can edit existing expenses',
                'group' => 'Financial Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delete Expenses',
                'slug' => 'expenses.delete',
                'description' => 'Can delete expense entries',
                'group' => 'Financial Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'View Financial Reports',
                'slug' => 'reports.financial',
                'description' => 'Can view financial reports and statements',
                'group' => 'Financial Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Vendor Management
            [
                'name' => 'View Vendors',
                'slug' => 'vendors.view',
                'description' => 'Can view vendor information',
                'group' => 'Vendor Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Create Vendors',
                'slug' => 'vendors.create',
                'description' => 'Can create new vendors',
                'group' => 'Vendor Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edit Vendors',
                'slug' => 'vendors.edit',
                'description' => 'Can edit vendor information',
                'group' => 'Vendor Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delete Vendors',
                'slug' => 'vendors.delete',
                'description' => 'Can delete vendors',
                'group' => 'Vendor Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Analytics & Reports
            [
                'name' => 'View Analytics',
                'slug' => 'analytics.view',
                'description' => 'Can view store analytics and reports',
                'group' => 'Analytics & Reports',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Export Reports',
                'slug' => 'analytics.export',
                'description' => 'Can export analytics data and reports',
                'group' => 'Analytics & Reports',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'View Sales Reports',
                'slug' => 'reports.sales',
                'description' => 'Can view sales reports and metrics',
                'group' => 'Analytics & Reports',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Customer Management
            [
                'name' => 'View Customers',
                'slug' => 'customers.view',
                'description' => 'Can view customer profiles and information',
                'group' => 'Customer Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Create Customers',
                'slug' => 'customers.create',
                'description' => 'Can create new customer accounts',
                'group' => 'Customer Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edit Customers',
                'slug' => 'customers.edit',
                'description' => 'Can edit customer information',
                'group' => 'Customer Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delete Customers',
                'slug' => 'customers.delete',
                'description' => 'Can delete customer accounts',
                'group' => 'Customer Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Role & Permission Management
            [
                'name' => 'View Roles',
                'slug' => 'roles.view',
                'description' => 'Can view roles and permissions',
                'group' => 'Role Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Create Roles',
                'slug' => 'roles.create',
                'description' => 'Can create new roles',
                'group' => 'Role Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edit Roles',
                'slug' => 'roles.edit',
                'description' => 'Can edit existing roles',
                'group' => 'Role Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delete Roles',
                'slug' => 'roles.delete',
                'description' => 'Can delete roles',
                'group' => 'Role Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Assign Roles',
                'slug' => 'roles.assign',
                'description' => 'Can assign roles to users',
                'group' => 'Role Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Settings Management
            [
                'name' => 'View Settings',
                'slug' => 'settings.view',
                'description' => 'Can view system settings',
                'group' => 'Settings',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edit Settings',
                'slug' => 'settings.edit',
                'description' => 'Can modify system settings',
                'group' => 'Settings',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Content Management
            [
                'name' => 'View Blogs',
                'slug' => 'blogs.view',
                'description' => 'Can view blog posts',
                'group' => 'Content Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Create Blogs',
                'slug' => 'blogs.create',
                'description' => 'Can create new blog posts',
                'group' => 'Content Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edit Blogs',
                'slug' => 'blogs.edit',
                'description' => 'Can edit blog posts',
                'group' => 'Content Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delete Blogs',
                'slug' => 'blogs.delete',
                'description' => 'Can delete blog posts',
                'group' => 'Content Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'View Menus',
                'slug' => 'menus.view',
                'description' => 'Can view navigation menus',
                'group' => 'Content Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Create Menus',
                'slug' => 'menus.create',
                'description' => 'Can create new menus',
                'group' => 'Content Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edit Menus',
                'slug' => 'menus.edit',
                'description' => 'Can edit navigation menus',
                'group' => 'Content Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delete Menus',
                'slug' => 'menus.delete',
                'description' => 'Can delete menus',
                'group' => 'Content Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'View Pages',
                'slug' => 'pages.view',
                'description' => 'Can view static pages',
                'group' => 'Content Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Create Pages',
                'slug' => 'pages.create',
                'description' => 'Can create new pages',
                'group' => 'Content Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Edit Pages',
                'slug' => 'pages.edit',
                'description' => 'Can edit static pages',
                'group' => 'Content Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Delete Pages',
                'slug' => 'pages.delete',
                'description' => 'Can delete pages',
                'group' => 'Content Management',
                'guard_name' => 'web',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($permissions as $permission) {
            // Check if permission already exists
            $exists = DB::table('permissions')
                ->where('slug', $permission['slug'])
                ->exists();
            
            if (!$exists) {
                DB::table('permissions')->insert($permission);
            }
        }
    }
}