import defaultTheme from "tailwindcss/defaultTheme";

module.exports = {
    darkMode: ["class"],
    content: [
        "./resources/js/seller/**/*.{js,ts,jsx,tsx}",
        "./resources/js/seller/**/*.js",
        "./resources/js/seller/**/*.tsx",
        "./resources/js/seller/**/*.vue",
    ],
    safelist: [
        "w-64",
        "w-1/2",
        "rounded-l-lg",
        "rounded-r-lg",
        "bg-gray-200",
        "grid-cols-4",
        "grid-cols-7",
        "h-6",
        "leading-6",
        "h-9",
        "leading-9",
        "shadow-lg",
        "bg-opacity-50",
        "dark:bg-opacity-80",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    DEFAULT: "#268844",
                    50: "#f2f9f4",
                    100: "#e0f0e4",
                    200: "#b3dbc0",
                    300: "#80c295",
                    400: "#4eaa69",
                    500: "#268844", // Primary dark green shade
                    600: "#206e39",
                    700: "#19542e",
                    800: "#123a22",
                    900: "#0b2116",
                },
            },
            fontFamily: {
                sans: [
                    "Inter",
                    "ui-sans-serif",
                    "system-ui",
                    "-apple-system",
                    "system-ui",
                    "Segoe UI",
                    "Roboto",
                    "Helvetica Neue",
                    "Arial",
                    "Noto Sans",
                    "sans-serif",
                    "Apple Color Emoji",
                    "Segoe UI Emoji",
                    "Segoe UI Symbol",
                    "Noto Color Emoji",
                ],
                body: [
                    "Inter",
                    "ui-sans-serif",
                    "system-ui",
                    "-apple-system",
                    "system-ui",
                    "Segoe UI",
                    "Roboto",
                    "Helvetica Neue",
                    "Arial",
                    "Noto Sans",
                    "sans-serif",
                    "Apple Color Emoji",
                    "Segoe UI Emoji",
                    "Segoe UI Symbol",
                    "Noto Color Emoji",
                ],
                mono: [
                    "ui-monospace",
                    "SFMono-Regular",
                    "Menlo",
                    "Monaco",
                    "Consolas",
                    "Liberation Mono",
                    "Courier New",
                    "monospace",
                ],
            },
            transitionProperty: {
                width: "width",
            },
            textDecoration: ["active"],
            minWidth: {
                kanban: "28rem",
            },
        },
    },
    plugins: [require("flowbite/plugin")],
};
