import { StoreType } from "@/js/types/storeType";

export const dummyStore: StoreType = {
	id: 3,
	name: 'Kacha Bazar',
	slug: 'kacha-bazar',
	domain: 'https://chologori-builder.test.com/stores/kacha-bazar',
	email: null,
	phone: null,
	location: null,
	status: 1,
	type: "e-commerce",
	description: null,
	currency: 'BDT',
	logo: 'http://chologori-builder.test/storage/file_storage/6790ec398797c_1737550905.png',
	dark_logo: null,
	primary_color: null,
	secondary_color: null,
	theme_id: 1,
	settings: null,
	social_media: [
		{
			id: 1,
			name: 'facebook',
			label: 'Facebook',
			username: 'chologori',
			url: 'https://www.facebook.com/',
			store_id: 3,
			created_at: '24 Jan, 2025 | 02:22 AM',
			updated_at: '24 Jan, 2025 | 02:22 AM',
		},
	],
	created_at: '22 Jan, 2025 | 01:01 PM',
	updated_at: '22 Jan, 2025 | 01:01 PM',
};
