import { ProductType } from "@type/productType";

export const dummyProducts: ProductType[] = [
	{
		id: 1,
		name: 'iPhone 14 Pro',
		slug: 'iphone-14-pro',
		sku: 'IPH14PRO',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/iphone-14-pro.jpg',
		attachments: [],
		category: {
			id: 1,
			store_id: 1,
			name: 'Electronics',
			slug: 'electronics',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 1,
			store_id: 1,
			name: 'Apple',
			slug: 'apple',
			image: 'http://chologori-builder.test/storage/seeders/brands/apple.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 999.99,
		discount_price: 999.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 2,
		name: 'Samsung Galaxy S23',
		slug: 'samsung-galaxy-s23',
		sku: 'GALAXYS23',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/samsung-galaxy-s23.jpg',
		attachments: [],
		category: {
			id: 1,
			store_id: 1,
			name: 'Electronics',
			slug: 'electronics',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 2,
			store_id: 1,
			name: 'Samsung',
			slug: 'samsung',
			image: 'http://chologori-builder.test/storage/seeders/brands/samsung.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 849.99,
		discount_price: 849.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 3,
		name: 'Nike Air Max 270',
		slug: 'nike-air-max-270',
		sku: 'NIKEAM270',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/nike-air-max-270.jpg',
		attachments: [],
		category: {
			id: 2,
			store_id: 1,
			name: 'Clothing',
			slug: 'clothing',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 3,
			store_id: 1,
			name: 'Nike',
			slug: 'nike',
			image: 'http://chologori-builder.test/storage/seeders/brands/nike.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 129.99,
		discount_price: 129.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 4,
		name: 'Adidas Ultraboost',
		slug: 'adidas-ultraboost',
		sku: 'ADIBOOST',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/adidas-ultraboost.jpg',
		attachments: [],
		category: {
			id: 2,
			store_id: 1,
			name: 'Clothing',
			slug: 'clothing',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 4,
			store_id: 1,
			name: 'Adidas',
			slug: 'adidas',
			image: 'http://chologori-builder.test/storage/seeders/brands/adidas.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 149.99,
		discount_price: 149.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 5,
		name: 'Sony WH-1000XM5',
		slug: 'sony-wh-1000xm5',
		sku: 'SONYXM5',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/sony-wh-1000xm5.jpg',
		attachments: [],
		category: {
			id: 1,
			store_id: 1,
			name: 'Electronics',
			slug: 'electronics',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 5,
			store_id: 1,
			name: 'Sony',
			slug: 'sony',
			image: 'http://chologori-builder.test/storage/seeders/brands/sony.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 299.99,
		discount_price: 299.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 6,
		name: 'Microsoft Surface Pro 9',
		slug: 'microsoft-surface-pro-9',
		sku: 'SURFACEPRO9',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/microsoft-surface-pro-9.jpg',
		attachments: [],
		category: {
			id: 1,
			store_id: 1,
			name: 'Electronics',
			slug: 'electronics',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 6,
			store_id: 1,
			name: 'Microsoft',
			slug: 'microsoft',
			image:
				'http://chologori-builder.test/storage/seeders/brands/microsoft.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 1099.99,
		discount_price: 1099.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 7,
		name: 'Gucci Leather Bag',
		slug: 'gucci-leather-bag',
		sku: 'GUCCIBAG01',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/gucci-leather-bag.jpg',
		attachments: [],
		category: {
			id: 15,
			store_id: 1,
			name: 'Travel & Luggage',
			slug: 'travel-luggage',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 7,
			store_id: 1,
			name: 'Gucci',
			slug: 'gucci',
			image: 'http://chologori-builder.test/storage/seeders/brands/gucci.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 1999.99,
		discount_price: 1999.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 8,
		name: 'Puma Running Shoes',
		slug: 'puma-running-shoes',
		sku: 'PUMASHOE01',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/puma-running-shoes.jpg',
		attachments: [],
		category: {
			id: 2,
			store_id: 1,
			name: 'Clothing',
			slug: 'clothing',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 8,
			store_id: 1,
			name: 'Puma',
			slug: 'puma',
			image: 'http://chologori-builder.test/storage/seeders/brands/puma.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 89.99,
		discount_price: 89.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 9,
		name: "L'Or\u00e9al Face Cream",
		slug: 'loreal-face-cream',
		sku: 'LOREALCREAM01',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/loreal-face-cream.jpg',
		attachments: [],
		category: {
			id: 4,
			store_id: 1,
			name: 'Beauty & Personal Care',
			slug: 'beauty-personal-care',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 9,
			store_id: 1,
			name: "L'Or\u00e9al",
			slug: 'loreal',
			image: 'http://chologori-builder.test/storage/seeders/brands/loreal.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 29.99,
		discount_price: 29.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 10,
		name: 'Coca-Cola Pack of 12',
		slug: 'coca-cola-pack-12',
		sku: 'COCACOLA12',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/coca-cola-pack-12.jpg',
		attachments: [],
		category: {
			id: 14,
			store_id: 1,
			name: 'Groceries',
			slug: 'groceries',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 10,
			store_id: 1,
			name: 'Coca-Cola',
			slug: 'coca-cola',
			image:
				'http://chologori-builder.test/storage/seeders/brands/coca-cola.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 8.99,
		discount_price: 8.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 11,
		name: 'Tesla Model Y',
		slug: 'tesla-model-y',
		sku: 'TESLAY01',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/tesla-model-y.jpg',
		attachments: [],
		category: {
			id: 9,
			store_id: 1,
			name: 'Automotive',
			slug: 'automotive',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 11,
			store_id: 1,
			name: 'Tesla',
			slug: 'tesla',
			image: 'http://chologori-builder.test/storage/seeders/brands/tesla.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 49999.99,
		discount_price: 49999.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 12,
		name: 'Toyota Corolla 2023',
		slug: 'toyota-corolla-2023',
		sku: 'TOYCOR23',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/toyota-corolla-2023.jpg',
		attachments: [],
		category: {
			id: 9,
			store_id: 1,
			name: 'Automotive',
			slug: 'automotive',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 12,
			store_id: 1,
			name: 'Toyota',
			slug: 'toyota',
			image: 'http://chologori-builder.test/storage/seeders/brands/toyota.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 22999.99,
		discount_price: 22999.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 13,
		name: 'Chanel No. 5 Perfume',
		slug: 'chanel-no-5',
		sku: 'CHANEL05',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/chanel-no-5.jpg',
		attachments: [],
		category: {
			id: 4,
			store_id: 1,
			name: 'Beauty & Personal Care',
			slug: 'beauty-personal-care',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 13,
			store_id: 1,
			name: 'Chanel',
			slug: 'chanel',
			image: 'http://chologori-builder.test/storage/seeders/brands/chanel.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 129.99,
		discount_price: 129.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 14,
		name: 'Intel Core i9 Processor',
		slug: 'intel-core-i9',
		sku: 'INTELI9',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/intel-core-i9.jpg',
		attachments: [],
		category: {
			id: 1,
			store_id: 1,
			name: 'Electronics',
			slug: 'electronics',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 14,
			store_id: 1,
			name: 'Intel',
			slug: 'intel',
			image: 'http://chologori-builder.test/storage/seeders/brands/intel.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 499.99,
		discount_price: 499.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
	{
		id: 15,
		name: 'Dell XPS 15',
		slug: 'dell-xps-15',
		sku: 'XPS15',
		short_description: null,
		description: null,
		thumbnail:
			'http://chologori-builder.test/storage/seeders/products/dell-xps-15.jpg',
		attachments: [],
		category: {
			id: 1,
			store_id: 1,
			name: 'Electronics',
			slug: 'electronics',
			type: 'product',
			has_parent: null,
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		brand: {
			id: 15,
			store_id: 1,
			name: 'Dell',
			slug: 'dell',
			image: 'http://chologori-builder.test/storage/seeders/brands/dell.jpg',
			created_at: '07 Feb, 2025 | 08:13 AM',
			updated_at: '07 Feb, 2025 | 08:13 AM',
		},
		has_in_stocks: 1,
		stock: null,
		status: 1,
		variants: null,
		is_trending: 0,
		has_discount: 0,
		discount_to: null,
		discount_type: null,
		discount_amount: null,
		price: 1599.99,
		discount_price: 1599.99,
		created_at: '07 Feb, 2025 | 08:13 AM',
		updated_at: '07 Feb, 2025 | 08:13 AM',
	},
];
